### ISSUE TITLE
Improvement in helper_functions.py

### ISSUE THREAD

**Issue by bhavya2021245** [NirDiamant/RAG_Techniques#13]
In the **"encode_from_string"** function these are some of the improvements i suggest
1.Add error handling to manage cases where the text splitting, embedding creation, or vector store creation might fail.
2.Validate the content input to ensure it's not empty and is of the expected type (string).

**Comment by NirDiamant** [comment]
Sounds good :) would you want to open a PR?

**Comment by bhavya2021245** [comment]
Sure. I'll take care of it shortly and let you know once it's up!
