### ISSUE TITLE
problem installing packages from requirements.txt on macOS

### ISSUE THREAD

**Issue by adedj** [NirDiamant/RAG_Techniques#26]
# Problem
There are issues when trying to install all the dependencies on a macOS.
python - 3.10
macOS - 14.6.1

Example:
**pip install -r requirements.txt**

`ERROR: Could not find a version that satisfies the requirement llama-index-multi-modal-llms-openai==0.2.2 (from versions: 0.0.1, 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0)
ERROR: No matching distribution found for llama-index-multi-modal-llms-openai==0.2.2`

If I change to llama-index-multi-modal-llms-openai==0.2.0

`ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
ERROR: No matching distribution found for pywin32==306`

If I try to remove pywin32 I receive other multiple conflicts.

**Comment by NirDiamant** [comment]
give it a try now :) thanks for @tevfikcagridural
