### ISSUE TITLE
Update from llama_index.core service_context to Settings

### ISSUE THREAD

**Issue by kimmeyh** [NirDiamant/RAG_Techniques#39]
In choose_chink_size.ipynb
The following code:
`    # create vector index
    llm = OpenAI(model="gpt-3.5-turbo")

    service_context = ServiceContext.from_defaults(llm=llm, chunk_size=chunk_size, chunk_overlap=chunk_size//5)
    vector_index = VectorStoreIndex.from_documents(
        eval_documents, service_context=service_context
    )`
Gives error:
ValueError: ServiceContext is deprecated. Use llama_index.settings.Settings instead, or pass in modules to local functions/methods/interfaces.
See the docs for updated usage/migration: 
https://docs.llamaindex.ai/en/stable/module_guides/supporting_modules/service_context_migration/
Can be replaced by:
`    llm = OpenAI(model="gpt-3.5-turbo")

    Settings.llm = llm
    Settings.chunk_size = chunk_size
    Settings.chunk_overlap = chunk_size // 5

    vector_index = VectorStoreIndex.from_documents(
        eval_documents, settings=Settings
    )`

**Comment by NirDiamant** [comment]
Can you please open a PR to fix this issue?

**Comment by kimmeyh** [comment]
Nir,

 

I cannot at this time.

 

However, I will consider contributing as soon as I can (probably 3 to 4 weeks).

 

Sincerely,

 

Harold

216-357-9227
