### ISSUE TITLE
AI assist trained on the repo

### ISSUE THREAD

**Issue by samyakkkk** [NirDiamant/RAG_Techniques#4]
Hi there! 

I've created an AI assist using [CommandDash](app.commanddash.io) to help anyone be able to understand and ask questions across the repo.

Sharing it [here](https://app.commanddash.io/agent/github_NirDiamant_RAG_Techniques) 🙌🏼 It could be helpful to learn the techniques better and apply it.

Also mentionable as a badge in the readme.

<a href="https://app.commanddash.io/agent/github_NirDiamant_RAG_Techniques"><img src="https://img.shields.io/badge/AI-Code%20Agent-EB9FDA"></a>

```
<a href="https://app.commanddash.io/agent/github_NirDiamant_RAG_Techniques"><img src="https://img.shields.io/badge/AI-Code%20Agent-EB9FDA"></a>
```

**Comment by NirDiamant** [comment]
that is so cool! adding this to the README!

**Comment by samyakkkk** [comment]
this repository is even cooler! thanks for creating it - super helpful!

Please feel free to close the issue.
