### ISSUE TITLE
Hard to build

### ISSUE THREAD

**Issue by JourneyGo** [NirDiamant/RAG_Techniques#67]
After trying for several times, still can not find a proper IMAGE to build and run all of these. 
Could anyone share an IMAGE with all dependences installed?

**Comment by NirDiamant** [comment]
Please note that the tutorials are independent, so you only need to install the dependencies for the specific techniques you plan to use. Initially, I thought it might be easier to install everything at once to cover all tutorials, but as the library has grown, I believe it's better to separate the dependencies. I’ll work on this or ask someone from the community to handle it soon.
