### ISSUE TITLE
Text-to-SQL addition?

### ISSUE THREAD

**Issue by julioasotodv** [NirDiamant/RAG_Techniques#7]
Hi, would it make sense to include text-to-sql or text-to-query variants in this list? Those can be RAG as well

**Comment by NirDiamant** [comment]
Hi, Sure. I find it interesting and valuable for many cases. Since currently the repo deals with only unstructured data, if you open a PR, please make sure to supply an appropriate use case example, and please follow the CONTRIBUTIONS file :)
